/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "AssetsBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "DATABASE_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GOOGLE_CLIENT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GOOGLE_CLIENT_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MERCADO_PAGO_ACCESS_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "RemixApp": {
      "type": "sst.aws.Remix"
      "url": string
    }
    "SECRET_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TOGETHER_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
